spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg-practice
    username: postgres
    password: 1234
    
  flyway:
    enabled: false 
    driver-class-name: org.postgresql.Driver
    baseline-on-migrate: true