spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg-practice
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    
  flyway:
    enabled: true 
    driver-class-name: org.postgresql.Driver
    
logging:
  level:
    root: info