spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg-practice
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    
  flyway:
    enabled: false 
    driver-class-name: org.postgresql.Driver
    baseline-on-migrate: true